# Generated by Django 5.0.6 on 2026-03-27 09:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0003_budget_and_expenses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBudgetPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('daily_allowance', models.DecimalField(decimal_places=2, help_text='Сколько «капает» на каждый день периода', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_budget_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='daily_budget_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='scope.dailybudgetperiod'),
        ),
        migrations.AddIndex(
            model_name='expenseentry',
            index=models.Index(fields=['daily_budget_period', 'date'], name='scope_expen_daily_b_ed32de_idx'),
        ),
    ]
