# Generated by Django 5.0.6 on 2026-04-27 14:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0007_api_access_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('color', models.CharField(default='#7C3AED', max_length=7)),
                ('icon', models.CharField(default='task_alt', max_length=80)),
                ('start_date', models.DateField(db_index=True)),
                ('duration_days', models.PositiveIntegerField(default=1, help_text='Длина «окна» цели в календарных днях от start_date', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3660)])),
                ('points_per_completion', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('weekday_mask', models.CharField(default='1111111', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BulletTaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-day', '-id'],
            },
        ),
        migrations.RenameIndex(
            model_name='apiaccesstoken',
            new_name='scope_apiac_user_id_c77492_idx',
            old_name='scope_apiac_user_id_7e8b2f_idx',
        ),
        migrations.AddField(
            model_name='bullettask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullet_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bullettaskcompletion',
            name='bullet_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='scope.bullettask'),
        ),
        migrations.AddIndex(
            model_name='bullettask',
            index=models.Index(fields=['user', 'start_date'], name='scope_bulle_user_id_f233c2_idx'),
        ),
        migrations.AddIndex(
            model_name='bullettaskcompletion',
            index=models.Index(fields=['bullet_task', 'day'], name='scope_bulle_bullet__8c5107_idx'),
        ),
        migrations.AddConstraint(
            model_name='bullettaskcompletion',
            constraint=models.UniqueConstraint(fields=('bullet_task', 'day'), name='unique_bullet_completion_day'),
        ),
    ]
