# Generated by Django 5.2.8 on 2026-09-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0008_bullet_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='auto_complete',
            field=models.BooleanField(default=False),
        ),
    ]
