# Generated by Django 5.2.8 on 2026-09-22 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0009_task_auto_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat',
            field=models.CharField(blank=True, choices=[('', 'Не повторять'), ('daily', 'Каждый день'), ('weekdays', 'По будням'), ('weekly', 'Каждую неделю'), ('biweekly', 'Раз в две недели'), ('monthly', 'Каждый месяц')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repeat_children', to='scope.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
